# Generated by Django 5.0.6 on 2024-05-31 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exportform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportdetail',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.exportform'),
        ),
        migrations.AddField(
            model_name='importform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importdetail',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.importform'),
        ),
        migrations.AddField(
            model_name='importdetail',
            name='order_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.orderdetail'),
        ),
        migrations.AddField(
            model_name='orderform',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.depot'),
        ),
        migrations.AddField(
            model_name='orderform',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.businesspartner'),
        ),
        migrations.AddField(
            model_name='orderform',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.orderform'),
        ),
        migrations.AddField(
            model_name='importform',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.orderform'),
        ),
        migrations.AddField(
            model_name='exportform',
            name='pricelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pricelist'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
        migrations.AddField(
            model_name='exportdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
        migrations.AddField(
            model_name='productdepot',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.depot'),
        ),
        migrations.AddField(
            model_name='productdepot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='pricelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pricelist'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.depot'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='importdetail',
            unique_together={('form', 'order_detail')},
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('form', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='exportdetail',
            unique_together={('form', 'product')},
        ),
    ]
