# Generated by Django 5.0.6 on 2024-05-30 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='export_form',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='export_detail',
            name='export',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.export_form'),
        ),
        migrations.AddField(
            model_name='import_form',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='import_detail',
            name='id_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.import_form'),
        ),
        migrations.AddField(
            model_name='import_detail',
            name='order_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.order_detail'),
        ),
        migrations.AddField(
            model_name='order_form',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.depot'),
        ),
        migrations.AddField(
            model_name='order_form',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.business_partner'),
        ),
        migrations.AddField(
            model_name='order_form',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order_form'),
        ),
        migrations.AddField(
            model_name='import_form',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.order_form'),
        ),
        migrations.AddField(
            model_name='export_form',
            name='pricelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pricelist'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
        migrations.AddField(
            model_name='export_detail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
        migrations.AddField(
            model_name='product_depot',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.depot'),
        ),
        migrations.AddField(
            model_name='product_depot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
        migrations.AddField(
            model_name='product_price',
            name='pricelist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pricelist'),
        ),
        migrations.AddField(
            model_name='product_price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='depot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.depot'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='import_detail',
            unique_together={('id_import', 'order_detail')},
        ),
        migrations.AlterUniqueTogether(
            name='order_detail',
            unique_together={('order', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='export_detail',
            unique_together={('export', 'product')},
        ),
    ]
