# Generated by Django 5.0.6 on 2024-06-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='expired_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
