# Generated by Django 5.0.6 on 2024-06-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelist',
            options={'ordering': ['expired_date']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='productdepot',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
