# Generated by Django 5.0.6 on 2024-06-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_productprice_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productdepot',
            constraint=models.CheckConstraint(check=models.Q(('inventory__gte', 0)), name='inventory_non_negative'),
        ),
    ]
