# Generated by Django 5.0.6 on 2024-06-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_productdepot_inventory_non_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderform',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
