name: Access server
on: push
jobs:
  access_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: actions/checkout@v2
        with:
          host: 192.168.1.27
          username: thanh
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 200m
          script: |
          cd /home/thanh/Desktop/backend/ 
          echo hello world > hello.txt
