name: Access server
on: push
jobs:
  access_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: 192.168.1.27
          username: thanh
          password: 123456
          port: 22
          command_timeout: 30m
          script: |
            ls
            cd /home/thanh/Desktop/backend/ 
            echo hello world > hello.txt
